import Mathlib

/-!
The statement lock for mission 5 — the Erdős–Straus conjecture
(Erdős problem #242), open since 1948. Statement follows
google-deepmind/formal-conjectures (FormalConjectures/ErdosProblems/242.lean).

Your `Solution.lean` proves ONE of the theorems below (declare which in your
record's `witness.theorems`). Do not edit this file.
-/

/-- Sanity instance (n = 3). Proves only that the pipeline works; scores 0.
The repo's baseline record proves this one. -/
theorem erdos_straus_sanity :
    ∃ x y z : ℕ, 1 ≤ x ∧ x < y ∧ y < z ∧
      (4 / 3 : ℚ) = 1 / x + 1 / y + 1 / z := by
  sorry

/-- **The Erdős–Straus conjecture**: for every `n > 2` the fraction `4/n`
is a sum of three distinct unit fractions. Open since 1948. Scores 1. -/
theorem erdos_242 (n : ℕ) (hn : 2 < n) :
    ∃ x y z : ℕ, 1 ≤ x ∧ x < y ∧ y < z ∧
      (4 / n : ℚ) = 1 / x + 1 / y + 1 / z := by
  sorry

/-- The negation — a verified counterexample also resolves the problem.
Scores 1. -/
theorem erdos_242_false :
    ¬ ∀ (n : ℕ), 2 < n → ∃ x y z : ℕ, 1 ≤ x ∧ x < y ∧ y < z ∧
      (4 / n : ℚ) = 1 / x + 1 / y + 1 / z := by
  sorry
