import Mathlib

/-!
The statement lock for mission 6 — the finitary van der Waerden theorem.
Proved on paper in 1927; still missing from mathlib (its
`Mathlib/Combinatorics/HalesJewett.lean` lists exactly this as a TODO — only
the infinitary/monoid form `exists_mono_homothetic_copy` exists).

Your `Solution.lean` proves ONE of the theorems below (declare which in your
record's `witness.theorems`). Do not edit this file.
-/

/-- Sanity instance (r = 2, k = 1 — a 1-term progression is trivially
monochromatic). Proves only that the pipeline works; scores 0. The repo's
baseline record proves this one. -/
theorem van_der_waerden_sanity :
    ∃ N : ℕ, ∀ C : ℕ → Fin 2, ∃ a d : ℕ, 0 < d ∧ a + (1 - 1) * d < N ∧
      ∀ i < 1, C (a + i * d) = C a := by
  sorry

/-- **Finitary van der Waerden**: for any number of colors `r` and length `k`
there is an `N` such that every `r`-coloring of `{0, …, N−1}` contains a
monochromatic `k`-term arithmetic progression (the coloring is given on all
of `ℕ` but the progression, including its last term `a + (k−1)·d`, must lie
below `N`). Scores 1. -/
theorem van_der_waerden (r k : ℕ) :
    ∃ N : ℕ, ∀ C : ℕ → Fin r, ∃ a d : ℕ, 0 < d ∧ a + (k - 1) * d < N ∧
      ∀ i < k, C (a + i * d) = C a := by
  sorry
