import Mathlib.NumberTheory.Real.Irrational

/-!
The statement lock for mission 4. Your `Solution.lean` must prove a theorem
with exactly this name and exactly this type; the comparator rejects anything
else. Do not edit this file.
-/

theorem sqrt2_irrational : Irrational (Real.sqrt 2) := by
  sorry
