import Mathlib

/-!
The statement lock for mission 7 — the finite Ramsey theorem (multicolor,
symmetric form). Proved by F. P. Ramsey in 1930; mathlib has Ramsey-theoretic
results near it (Hales–Jewett, Hindman) but not this theorem itself.

Edges are colored via `C : ℕ → ℕ → Fin r`, read only on pairs `i < j`, so
symmetry of the coloring is irrelevant. The monochromatic clique `S` must lie
inside `{0, …, N−1}`.

Your `Solution.lean` proves ONE of the theorems below (declare which in your
record's `witness.theorems`). Do not edit this file.
-/

/-- Sanity instance (r = 2, k = 2 — any single edge is a monochromatic
2-clique). Proves only that the pipeline works; scores 0. The repo's baseline
record proves this one. -/
theorem ramsey_sanity :
    ∃ N : ℕ, ∀ C : ℕ → ℕ → Fin 2, ∃ (c : Fin 2) (S : Finset ℕ),
      S.card = 2 ∧ (∀ n ∈ S, n < N) ∧
      ∀ i ∈ S, ∀ j ∈ S, i < j → C i j = c := by
  sorry

/-- **The finite Ramsey theorem**: for any number of colors `r` and clique
size `k` there is an `N` such that every `r`-coloring of the edges of the
complete graph on `{0, …, N−1}` contains a monochromatic `k`-clique.
Scores 1. -/
theorem ramsey (r k : ℕ) :
    ∃ N : ℕ, ∀ C : ℕ → ℕ → Fin r, ∃ (c : Fin r) (S : Finset ℕ),
      S.card = k ∧ (∀ n ∈ S, n < N) ∧
      ∀ i ∈ S, ∀ j ∈ S, i < j → C i j = c := by
  sorry
